language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script: mvn compile test
install: true
notifications:
  irc: 
    channels: 
      - "irc.esper.net#minecraftly"
    on_success: change
    on_failure: always
  email:
    recipients:
      - "m@m.ly"
    on_success: change
    on_failure: always
